### ISSUE TITLE
Generate docs from doctests

### ISSUE THREAD

**Issue by rbval** [hCaptcha/hmt-escrow#72]
# Description
A lot of our tests are written as doctests (https://docs.python.org/3/library/doctest.html). It would be good to generate documentation from these tests automatically.

Here are few example options to choose from:
- http://www.sphinx-doc.org/en/master/index.html
- https://github.com/BurntSushi/pdoc
- https://github.com/twisted/pydoctor
- http://www.stack.nl/~dimitri/doxygen/index.html

Any other ones can be used as well.

# Todo
1. Choose a python doc generation software
2. Generate docs from our docstrings found in the python packages
3. Update README

**Comment by posix4e** [comment]
agreed. i think someone could simplify publish it to the github page

**Comment by gaieges** [comment]
As I noted to @rbval in DM- I don't find autogen docs to be very useful, but get great amounts of value from the human docs.  

That being said, if we have the doctests, then its a no brainer to add in something like this.

**Comment by bxabi** [comment]
Hi! I started to look at this issue.
Sphinx seems to be widely used, and has support for the doctests. It also can be used to create a readthedocs.io style documentation hosted on that site, which many projects seem to use.
https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html
So I think I could set it up.

**Comment by bxabi** [comment]
I have 1-2 questions to clarify.
Are the files/modules which should be documented the eth_bridge.py, job.py, kvstore_abi.py and storage.py?
If that's right, it seems that sphinx imports the files, which means that it runs the code which is not in a function, and this causes the doc generation to fail.

When I put that code in a function, the doc generation works. So I could do this, but I suppose this effects other parts of the system which imports this code, because it would have to call an initialization method, which is currently executed just by importing.

**Comment by rbval** [comment]
Hi @bxabi and thanks for the interest. The ones that need documenting are: `eth_bridge.py`, `job.py`, `storage.py`. `kvstore_abi.py` doesn't need to be documented.

**Comment by rbval** [comment]
Would prefer not changing the existing logic with a wrapper function.

**Comment by bxabi** [comment]
I don't know how this code is used, but it looks like a module which is imported by other code.
Isn't it bad practice in general to have code running at import (especially code connecting to network services)?

**Comment by bxabi** [comment]
This is the section talking about the import: https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#module-sphinx.ext.autodoc

So in the eth_bridge the contract compilation, and in the storage the connect have to be wrapped (or all initialization code)
Then the generated doc looks like this:
![image](https://user-images.githubusercontent.com/11303766/75604811-07010100-5add-11ea-8f4a-446ae8441326.png)

As I see the syntax may not match exactly, the lines starting with <<< and ... should be shown differently or skipped, right?

**Comment by posix4e** [comment]
Sorry for the delay getting back to you. Wanna restate how we can best help?

**Comment by bxabi** [comment]
So the question is what would be the preferred way to make 2 statements conditional, to not run when the autodoc imports the files. The 2 statements are:

- IPFS_CLIENT = _connect(IPFS_HOST, IPFS_PORT) in the storage.py,

- CONTRACTS = compile_files([
        "{}/Escrow.sol".format(CONTRACT_FOLDER),
        "{}/EscrowFactory.sol".format(CONTRACT_FOLDER),
        "{}/HMToken.sol".format(CONTRACT_FOLDER),
        "{}/HMTokenInterface.sol".format(CONTRACT_FOLDER),
        "{}/SafeMath.sol".format(CONTRACT_FOLDER)
    ]) in the eth_brigde.

Can the files detect somehow that they are imported by the autodoc and disable this conditionally, or is there a more general solution?

Otherwise these statements fail, and the doc is not generated.
Alternatively an environment is needed where those statements succeed to connect to the specific services, but that seems an overkill for creating docs.

**Comment by posix4e** [comment]
@bxabi yea that sounds good. Wanna make the change?

**Comment by bxabi** [comment]
Yes I will prepare it. From the answer it seems I can choose the solution which I consider best, and hopefully it will pass the review.

**Comment by rbval** [comment]
Can you show how you intend to do the conditional for autodoc? Seems reasonable to me.

**Comment by bxabi** [comment]
First I just wrapped the initialization commands in a method, so the help can be generated, but of course this breaks the code using these modules, because they don't call it.
Actually now I'm thinking it would be better to make these files classes. Then the initialization can go in the constructor.
Should I do that?

**Comment by bxabi** [comment]
If the callers can't be changed, we could work around it, having a script to generate the docs. The script would disable the initialization part, creates the docs, and restores the real code.
I don't like this hack, but it would work.

**Comment by rbval** [comment]
I think a script would make sense, we could land it in bin/ folder.

**Comment by bxabi** [comment]
Ok, I can do that today and update the pull request.

**Comment by posix4e** [comment]
Done!
